#!/bin/bash
#firejail --name=fire --noprofile --x11=xephyr  --net=enp1s5 --netfilter=/etc/firejail/nolocal.net --private firefox &

# https://anyon3.github.io/firejail.html
# firejail --name=ff --noprofile --net=enp1s5 --netfilter=/etc/firejail/nolocal.net --ip=192.168.178.22 --dns=192.168.178.21:53  --nogroups --x11=xephyr  --machine-id --noroot --caps.drop=all --seccomp  --private-home=~/firejail/ --private-dev --private-tmp --ipc-namespace firefox --new-instance $* & 


if [[ "$1" -eq "new" ]]; then
	cp -R ~/firetor/tor/Browser/Downloads/* ~/Downloads
	rm -rf  ~/firetor/tor
	mkdir ~/firetor
	cp -R ~/tor ~/firetor
fi

arr=(
	--name=torbrowser 
	--netfilter=/etc/firejail/nolocal.net
	--net=ens3
	--noprofile  
	--nogroups 
	--x11=xephyr
	--xephyr-screen=1276x980
	--machine-id 
	--noroot 
	--caps.drop=all 
	--seccomp  
	--private=~/firetor/
	--private-dev 
	--private-tmp  
	--nodbus
	--ipc-namespace
	#~/.bin/tor-browser_en-US/Browser/firefox  
	openbox
)

firejail "${arr[@]}" &
